"""add_picker_session_columns

Revision ID: 033f5db93d4d
Revises: 22d9227fd839
Create Date: 2025-08-19 16:11:02.954323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033f5db93d4d'
down_revision = '22d9227fd839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expire_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('polling_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('picking_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_items_set', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.drop_column('media_items_set')
        batch_op.drop_column('picking_config_json')
        batch_op.drop_column('polling_config_json')
        batch_op.drop_column('expire_time')

    # ### end Alembic commands ###
