"""GoogleAccount実装

Revision ID: 1a83d2e086b5
Revises: 37a526f2f077
Create Date: 2025-08-12 17:20:35.405918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a83d2e086b5'
down_revision = '37a526f2f077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_account', schema=None) as batch_op:
        # 既存カラム(email, scopes)の追加はスキップ
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'inactive', 'revoked'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('oauth_token_json',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('account_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_email', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('oauth_token_json',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('active', 'inactive', 'revoked'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)
       # 既存カラム(scopes, email)の削除はスキップ

    # ### end Alembic commands ###
