"""mod required

Revision ID: 2d4b44385c9a
Revises: 8e7e76f7dfa2
Create Date: 2025-08-20 13:10:59.110105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d4b44385c9a'
down_revision = '8e7e76f7dfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
