"""add_request_id_to_log.py

Revision ID: 316f1d48cbe9
Revises: f2b317d264e2
Create Date: 2025-08-19 11:35:26.186465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316f1d48cbe9'
down_revision = 'f2b317d264e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
