"""Remove unique constraint on email and add composite unique constraint for user_id and email

Revision ID: 39773f220464
Revises: b0a2344d7929
Create Date: 2025-08-28 22:57:20.425033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39773f220464'
down_revision = 'b0a2344d7929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_unique_constraint('uq_user_google_email', ['user_id', 'email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_account', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_email', type_='unique')
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
