"""unified_media_model_restructure

Revision ID: 4344a1c01532
Revises: 8dc9f9ae9554
Create Date: 2025-08-29 19:42:19.503702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4344a1c01532'
down_revision = '8dc9f9ae9554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # まず、NULL値にデフォルト値を設定
    connection = op.get_bind()
    
    # Boolean型カラムのNULL値を適切な値に設定
    connection.execute(sa.text("UPDATE media SET is_video = 0 WHERE is_video IS NULL"))
    connection.execute(sa.text("UPDATE media SET is_deleted = 0 WHERE is_deleted IS NULL"))
    connection.execute(sa.text("UPDATE media SET has_playback = 0 WHERE has_playback IS NULL"))
    connection.execute(sa.text("UPDATE media SET imported_at = created_at WHERE imported_at IS NULL"))
    
    with op.batch_alter_table('media', schema=None) as batch_op:
        # 新しいカラムを追加（まずはNULL許可で）
        batch_op.add_column(sa.Column('source_type', sa.Enum('local', 'google_photos', name='media_source_type'), nullable=True))
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('camera_make', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('camera_model', sa.String(length=255), nullable=True))
        
        # 既存カラムをNOT NULLに変更
        batch_op.alter_column('is_video',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('imported_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('has_playback',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # 既存データのsource_typeを設定
    # google_media_idがあるものはgoogle_photos、ないものはlocal
    connection.execute(
        sa.text("UPDATE media SET source_type = 'google_photos' WHERE google_media_id IS NOT NULL")
    )
    connection.execute(
        sa.text("UPDATE media SET source_type = 'local' WHERE google_media_id IS NULL")
    )
    
    # local_rel_pathからfilenameを抽出
    connection.execute(
        sa.text("""
            UPDATE media 
            SET filename = SUBSTRING_INDEX(local_rel_path, '/', -1) 
            WHERE local_rel_path IS NOT NULL AND filename IS NULL
        """)
    )
    
    # source_typeをNOT NULLに変更
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.Enum('local', 'google_photos', name='media_source_type'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('has_playback',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('imported_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_video',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('camera_model')
        batch_op.drop_column('camera_make')
        batch_op.drop_column('filename')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
