"""change fk

Revision ID: 446c8706cd16
Revises: aece2f64b5f4
Create Date: 2025-08-20 10:52:44.783284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '446c8706cd16'
down_revision = 'aece2f64b5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picked_media_item_id', sa.String(length=255), nullable=False))
        batch_op.create_foreign_key(None, 'picked_media_item', ['picked_media_item_id'], ['id'])

    with op.batch_alter_table('picked_media_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('picked_media_item_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('media_file_metadata_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picked_media_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_file_metadata_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('picked_media_item_ibfk_1'), 'media_file_metadata', ['media_file_metadata_id'], ['id'])

    with op.batch_alter_table('media_file_metadata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('picked_media_item_id')

    # ### end Alembic commands ###
