"""add dl task

Revision ID: 58910e99386a
Revises: e448f741e54e
Create Date: 2025-08-20 15:06:26.838190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58910e99386a'
down_revision = 'e448f741e54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picker_import_task',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('picker_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('picked_media_item_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'skipped', 'expired', 'dup', name='picker_import_task_status'), server_default='queued', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('base_url_snapshot', sa.Text(), nullable=True),
    sa.Column('cursor', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['picked_media_item_id'], ['picked_media_item.id'], ),
    sa.ForeignKeyConstraint(['picker_session_id'], ['picker_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('picker_session_id', 'picked_media_item_id', name='uk_task_session_item')
    )
    with op.batch_alter_table('picker_import_task', schema=None) as batch_op:
        batch_op.create_index('idx_task_session_status', ['picker_session_id', 'status'], unique=False)

    with op.batch_alter_table('picker_import_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picker_import_item_picker_session_id'))
        batch_op.drop_index(batch_op.f('uniq_picker_session_media'))

    op.drop_table('picker_import_item')
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    op.create_table('picker_import_item',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('picker_session_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('media_item_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['picker_session_id'], ['picker_session.id'], name=op.f('picker_import_item_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('picker_import_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uniq_picker_session_media'), ['picker_session_id', 'media_item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_picker_import_item_picker_session_id'), ['picker_session_id'], unique=False)

    with op.batch_alter_table('picker_import_task', schema=None) as batch_op:
        batch_op.drop_index('idx_task_session_status')

    op.drop_table('picker_import_task')
    # ### end Alembic commands ###
