"""Allow null google_media_id and add local_file_path to PickerSelection for local import support

Revision ID: 5d8d71aa1fad
Revises: 9c4c0da481ae
Create Date: 2025-08-29 02:01:47.395175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d8d71aa1fad'
down_revision = '9c4c0da481ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_selection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_file_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('local_filename', sa.String(length=500), nullable=True))
        batch_op.alter_column('google_media_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_selection', schema=None) as batch_op:
        batch_op.alter_column('google_media_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('local_filename')
        batch_op.drop_column('local_file_path')

    # ### end Alembic commands ###
