"""Add refresh token field to User model

Revision ID: 8dc9f9ae9554
Revises: e5fd5ff05da7
Create Date: 2025-08-29 17:57:51.214686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dc9f9ae9554'
down_revision = 'e5fd5ff05da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_account', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('refresh_token_hash')

    with op.batch_alter_table('google_account', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###
