"""delete complete at

Revision ID: 8e7e76f7dfa2
Revises: 446c8706cd16
Create Date: 2025-08-20 12:55:53.325117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e7e76f7dfa2'
down_revision = '446c8706cd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
