"""Allow nullable account_id for local import sessions

Revision ID: 9c4c0da481ae
Revises: 39773f220464
Create Date: 2025-08-29 01:34:25.177299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c4c0da481ae'
down_revision = '39773f220464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picker_session', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###
