"""delete_create_at

Revision ID: aece2f64b5f4
Revises: 4397bd577587
Create Date: 2025-08-20 10:07:14.834233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aece2f64b5f4'
down_revision = '4397bd577587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picked_media_item', schema=None) as batch_op:
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picked_media_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
