"""Add user_id to google_account table

Revision ID: b0a2344d7929
Revises: 9a9a54990c3e
Create Date: 2025-08-28 22:53:37.501064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a2344d7929'
down_revision = '9a9a54990c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_account', schema=None) as batch_op:
        # まず、user_id カラムをNULL可能として追加
        batch_op.add_column(sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
    
    # 既存のGoogle Accountレコードに適切なuser_idを設定
    # 最初のユーザー（ID: 1）にリンクする
    op.execute("UPDATE google_account SET user_id = 1 WHERE user_id IS NULL")
    
    # user_idカラムをNOT NULLに変更（MySQL用に型も指定）
    with op.batch_alter_table('google_account', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
                              nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
