"""add_media_source_and_camera_fields

Revision ID: c097ec524158
Revises: 8dc9f9ae9554
Create Date: 2025-08-29 19:46:05.667270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c097ec524158'
down_revision = '8dc9f9ae9554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # まず、NULL値にデフォルト値を設定
    connection = op.get_bind()
    
    # Boolean型カラムのNULL値を適切な値に設定
    connection.execute(sa.text("UPDATE media SET is_deleted = 0 WHERE is_deleted IS NULL"))
    connection.execute(sa.text("UPDATE media SET has_playback = 0 WHERE has_playback IS NULL"))
    
    # source_typeがNULLの場合、google_media_idの有無で判定
    connection.execute(
        sa.text("UPDATE media SET source_type = 'google_photos' WHERE google_media_id IS NOT NULL AND source_type IS NULL")
    )
    connection.execute(
        sa.text("UPDATE media SET source_type = 'local' WHERE google_media_id IS NULL AND source_type IS NULL")
    )
    
    # local_rel_pathからfilenameを抽出（まだ設定されていない場合）
    connection.execute(
        sa.text("""
            UPDATE media 
            SET filename = SUBSTRING_INDEX(local_rel_path, '/', -1) 
            WHERE local_rel_path IS NOT NULL AND (filename IS NULL OR filename = '')
        """)
    )
    
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=mysql.ENUM('local', 'google_photos'),
               nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('has_playback',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('has_playback',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('source_type',
               existing_type=mysql.ENUM('local', 'google_photos'),
               nullable=True)

    # ### end Alembic commands ###
