"""add unique

Revision ID: e448f741e54e
Revises: 2d4b44385c9a
Create Date: 2025-08-20 13:31:12.981448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e448f741e54e'
down_revision = '2d4b44385c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_file_metadata', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['picked_media_item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_file_metadata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
