"""add_status_columns

Revision ID: fb95891d3b48
Revises: 033f5db93d4d
Create Date: 2025-08-19 23:57:11.947215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb95891d3b48'
down_revision = '033f5db93d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_metadata',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.Column('aperture_f_number', sa.Float(), nullable=True),
    sa.Column('iso_equivalent', sa.Integer(), nullable=True),
    sa.Column('exposure_time', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_metadata',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.Enum('UNSPECIFIED', 'PROCESSING', 'READY', 'FAILED', name='video_processing_status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_file_metadata',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('camera_make', sa.String(length=255), nullable=True),
    sa.Column('camera_model', sa.String(length=255), nullable=True),
    sa.Column('photo_metadata_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('video_metadata_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['photo_metadata_id'], ['photo_metadata.id'], ),
    sa.ForeignKeyConstraint(['video_metadata_id'], ['video_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picked_media_item',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('TYPE_UNSPECIFIED', 'PHOTO', 'VIDEO', name='picked_media_item_type'), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'imported', 'dup', 'failed', 'expired', 'skipped', name='picked_media_item_status'), server_default='pending', nullable=False),
    sa.Column('media_file_metadata_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['media_file_metadata_id'], ['media_file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picked_media_item')
    op.drop_table('media_file_metadata')
    op.drop_table('video_metadata')
    op.drop_table('photo_metadata')
    # ### end Alembic commands ###
