name: Build Photonest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build app Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_HASH_FULL=$(git rev-parse HEAD)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          COMMIT_DATE=$(git log -1 --format=%ci)
          BUILD_DATE=$(date -Iseconds)

          docker buildx build \
            --platform linux/amd64 \
            --build-arg COMMIT_HASH="$COMMIT_HASH" \
            --build-arg COMMIT_HASH_FULL="$COMMIT_HASH_FULL" \
            --build-arg BRANCH="$BRANCH" \
            --build-arg COMMIT_DATE="$COMMIT_DATE" \
            --build-arg BUILD_DATE="$BUILD_DATE" \
            -t photonest:latest . \
            --load

          docker save photonest:latest -o photonest-latest.tar
          chmod 644 photonest-latest.tar

      - name: Build DB Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t photonest-db:latest ./db \
            --load

          docker save photonest-db:latest -o photonest-db-latest.tar
          chmod 644 photonest-db-latest.tar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: photonest-images
          path: |
            photonest-latest.tar
            photonest-db-latest.tar
